#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
sys.path.append('si')

import db
import api

import cgi
import time
import datetime

params = cgi.FieldStorage()
inviteid = params.getvalue('id')

validinvite = False
publicInvite = False
nowts = time.time()

results = db.select('invites',['created','validity'],{'inviteid':inviteid,'accepted':'is null'},'created DESC')
for result in results:
  createdts = time.mktime(datetime.datetime.strptime(result['created'], "%Y-%m-%d %H:%M:%S").timetuple())
  validtill = createdts + (result['validity'] * 60 * 60 * 24)
  if validtill < nowts:
    db.delete('invites',{'inviteid':result['inviteid']})
    pub = db.select('publics',['inviteid'],{'inviteid':result['inviteid']},'inviteid')
    for res in pub:
      db.delete('publics',{'inviteid':result['inviteid']})
  else:
    validinvite = True
    pub = db.select('publics',['ask_phone', 'ask_mail', 'ask_reddit', 'ask_fb', 'ask_twitt', 'ask_insta'],{'inviteid':inviteid},'inviteid')
    for res in pub:
      publicInvite = {'ask_phone':res['ask_phone'],'ask_mail':res['ask_mail'],'ask_reddit':res['ask_reddit'],'ask_fb':res['ask_fb'],'ask_twitt':res['ask_twitt'],'ask_insta':res['ask_insta']}

data = {'id':inviteid,'valid':validinvite,'public':publicInvite}
api.output(data)
