#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
sys.path.append('si')

import db
import api

import cgi

params = cgi.FieldStorage()

account = params.getvalue('account')
delid   = params.getvalue('delid')

if len(account) > 2:
  results = db.select('invites',['inviteid'],{'account':account},'created DESC')
  for result in results:
    db.delete('invites',{'inviteid':result['inviteid']})
    pub = db.select('publics',['inviteid'],{'inviteid':result['inviteid']},'inviteid')
    for res in pub:
      db.delete('publics',{'inviteid':result['inviteid']})

if delid:
  results = db.select('invites',['inviteid'],{'inviteid':delid},'created DESC')
  for result in results:
    db.delete('invites',{'inviteid':result['inviteid']})
    pub = db.select('publics',['inviteid'],'inviteid':result['inviteid'],'inviteid')
    for res in pub:
      db.delete('publics',{'inviteid':result['inviteid']})

data = {}
api.output(data)
