#!/usr/bin/python3
# -*- coding: UTF-8 -*-

import sys
sys.path.append('si')

import mailer
import db
import api
import errorHandler

import cgi
import time
import datetime

params = cgi.FieldStorage()
inviteid = params.getvalue('id')
account  = params.getvalue('account')
owner    = params.getvalue('owner')
active   = params.getvalue('active')
posting  = params.getvalue('posting')
memo     = params.getvalue('memo')

validinvite = False
savedinvite = False
nowts = time.time()

results = db.select('invites',['created','validity','usermail'],{'inviteid':inviteid,'accepted': 'is null'},'created DESC')
for result in results:
  createdts = time.mktime(datetime.datetime.strptime(result['created'], "%Y-%m-%d %H:%M:%S").timetuple())
  validtill = createdts + (result['validity'] * 60 * 60 * 24)
  if validtill < nowts:
    db.delete('invites',{'inviteid':result['inviteid']})
  else:
    validinvite = True
    usermail = result['usermail']

if validinvite != True:
  errorHandler.throwError('No valid invite found')

db.update('invites',{'account':account,'owner':owner,'active':active,'posting':posting,'memo':memo,'accepted':'CURRENT_TIMESTAMP'},{'inviteid':inviteid})
savedinvite = True
  
mailer.sendmail(usermail,'One of your steem invitations was accepted',"Visit https://steeminvite.com/ to finish account creation.")

data = {'id':inviteid,'saved':savedinvite}
api.output(data)